### ISSUE TITLE
Error with getCPUInfo

### ISSUE THREAD

**Issue by endmvp** [oscmejia/os-utils#14]
I have error on use cpuUsage 
```
node_modules\os-utils\lib\osutils.js:198
        user += cpus[cpu].times.user;
                                ^

TypeError: Cannot read property 'user' of undefined
    at getCPUInfo (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\node_modules\os-utils\lib\osutils.js:198:33)
    at getCPUUsage (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\node_modules\os-utils\lib\osutils.js:167:18)
    at Object.exports.cpuUsage (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\node_modules\os-utils\lib\osutils.js:162:5)
    at Timeout._onTimeout (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\bot\Structures\Site.js:45:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

And I fixed it by replacing the line:
```
for (var cpu in cpus) {
        user + = cpus [cpu] .times.user;
        good + = cpu [cpu] .times.nice;
        sys + = cpus [cpu] .times.sys;
        irq + = cpus [cpu] .times.irq;
        idle + = cpus [cpu] .times.idle;
    }
```
to
```
    cpus.forEach(cpu => {
        user += cpu.times.user;
        nice += cpu.times.nice;
        sys += cpu.times.sys;
        irq += cpu.times.irq;
        idle += cpu.times.idle;
    })
```

**Comment by saru2020** [comment]
> I have error on use cpuUsage
> 
> ```
> node_modules\os-utils\lib\osutils.js:198
>         user += cpus[cpu].times.user;
>                                 ^
> 
> TypeError: Cannot read property 'user' of undefined
>     at getCPUInfo (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\node_modules\os-utils\lib\osutils.js:198:33)
>     at getCPUUsage (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\node_modules\os-utils\lib\osutils.js:167:18)
>     at Object.exports.cpuUsage (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\node_modules\os-utils\lib\osutils.js:162:5)
>     at Timeout._onTimeout (D:\Other\Development\Projects\BotDiscord\Kristal-Alp.-\bot\Structures\Site.js:45:12)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> ```
> 
> And I fixed it by replacing the line:
> 
> ```
> for (var cpu in cpus) {
>         user + = cpus [cpu] .times.user;
>         good + = cpu [cpu] .times.nice;
>         sys + = cpus [cpu] .times.sys;
>         irq + = cpus [cpu] .times.irq;
>         idle + = cpus [cpu] .times.idle;
>     }
> ```
> 
> to
> 
> ```
>     cpus.forEach(cpu => {
>         user += cpu.times.user;
>         nice += cpu.times.nice;
>         sys += cpu.times.sys;
>         irq += cpu.times.irq;
>         idle += cpu.times.idle;
>     })
> ```

I faced the same issue and the solution given by @Kristalkill  also works, why don't we have this merged? @oscmejia
